[Service]
Environment=SPRUCE_GOOSE_DERIVATION_EXECUTOR_ACTOR=sprucegoose-derivation-v1
Environment=SPRUCE_GOOSE_OBAN_ENABLED=true
ExecStart=
ExecStart=/usr/bin/env SPRUCE_GOOSE_OBAN_ENABLED=true SPRUCE_GOOSE_DERIVATION_EXECUTOR_ACTOR=sprucegoose-derivation-v1 /home/admin-papa/sprucegoose-rel/bin/spruce_goose start
