ExUnit.start()
Code.require_file("../lib/spruce_goose/release_provenance.ex", __DIR__)
Code.require_file("../lib/spruce_goose/release_validator.ex", __DIR__)

defmodule SpruceGoose.ReleaseValidatorTest do
  use ExUnit.Case, async: true
  alias SpruceGoose.{ReleaseProvenance, ReleaseValidator}

  @a String.duplicate("a", 64)
  @b String.duplicate("b", 64)
  @commit String.duplicate("c", 40)
  @tree String.duplicate("d", 40)

  setup do
    root = tmp()

    migrations = [
      %{
        "path" => "priv/repo/migrations/20260705142134_spike_init_extensions_1.exs",
        "sha256" => @a
      },
      %{"path" => "priv/repo/migrations/20260705142135_spike_init.exs", "sha256" => @b}
    ]

    %{root: root, migrations: migrations, provenance: provenance(migrations)}
  end

  test "archive inspection requires exactly one uniquely named provenance member", %{
    provenance: p
  } do
    bytes = provenance_bytes(p)

    assert {:ok, %{member: "releases/9.8.7/governed-provenance.json"}} =
             ReleaseValidator.inspect_archive_bytes(
               tar([{~c"releases/9.8.7/governed-provenance.json", bytes}])
             )

    assert {:error, "archive contains no governed provenance member"} =
             ReleaseValidator.inspect_archive_bytes(tar([{~c"other", "x"}]))

    assert {:error, "archive contains multiple governed provenance members"} =
             ReleaseValidator.inspect_archive_bytes(
               tar([
                 {~c"releases/a/governed-provenance.json", bytes},
                 {~c"releases/b/governed-provenance.json", bytes}
               ])
             )

    assert {:error, "archive contains duplicate member names"} =
             ReleaseValidator.inspect_archive_bytes(
               tar([
                 {~c"releases/a/governed-provenance.json", bytes},
                 {~c"releases/a/governed-provenance.json", bytes}
               ])
             )
  end

  test "archive generated by the build GNU tar pipeline exposes canonical provenance member", %{
    root: root,
    provenance: p
  } do
    release = Path.join(root, "release")
    member = "releases/9.8.7/governed-provenance.json"
    File.mkdir_p!(Path.dirname(Path.join(release, member)))
    File.write!(Path.join(release, member), provenance_bytes(p))
    archive = Path.join(root, "exact-builder-pipeline.tar.gz")

    {_, 0} =
      System.cmd(
        "bash",
        [
          "-c",
          "set -o pipefail; cd \"$1\"; mapfile -d '' entries < <(find . -mindepth 1 -maxdepth 1 -printf '%f\\0' | LC_ALL=C sort -z); TZ=UTC LC_ALL=C tar --sort=name --mtime=@0 --owner=0 --group=0 --numeric-owner --format=gnu -cf - -- \"${entries[@]}\" | gzip -n -9 >\"$2\"",
          "bash",
          release,
          archive
        ],
        stderr_to_stdout: true
      )

    assert {:ok, %{member: ^member}} =
             archive |> File.read!() |> ReleaseValidator.inspect_archive_bytes()
  end

  test "rejects noncanonical and ambiguous provenance member representations", %{provenance: p} do
    bytes = provenance_bytes(p)
    canonical = ~c"releases/9.8.7/governed-provenance.json"

    for alternative <- [
          ~c"./releases/9.8.7/governed-provenance.json",
          ~c"x/releases/9.8.7/governed-provenance.json",
          ~c"releases/../governed-provenance.json",
          ~c"releases/9.8.7/../9.8.7/governed-provenance.json"
        ] do
      assert {:error, "archive contains noncanonical governed provenance member"} =
               ReleaseValidator.inspect_archive_bytes(tar([{alternative, bytes}]))

      assert {:error, "archive contains noncanonical governed provenance member"} =
               ReleaseValidator.inspect_archive_bytes(
                 tar([{canonical, bytes}, {alternative, bytes}])
               )
    end
  end

  test "rejects receipt archive filename, archive digest, and provenance digest mismatches",
       context do
    fixture = fixture(context)

    assert_error(fixture,
      receipt_update: &put_in(&1, ["archive", "filename"], "wrong.tar.gz"),
      message: "archive filename mismatch"
    )

    assert_error(fixture,
      receipt_update: &put_in(&1, ["archive", "sha256"], @a),
      message: "archive sha256 mismatch"
    )

    assert_error(fixture,
      receipt_update: &Map.put(&1, "provenance_sha256", @b),
      message: "provenance sha256 mismatch"
    )
  end

  test "dirty provenance rejects by default and explicit override is nontransferable", context do
    dirty = put_in(context.provenance, ["source", "dirty"], true)
    f = fixture(%{context | provenance: dirty})
    assert {:error, "dirty source is rejected without explicit override"} = validate(f)

    assert {:ok, %{classification: "non-transferable-dirty-evidence"}} =
             validate(f, allow_dirty: true)
  end

  test "commit and tree mismatches reject", context do
    f = fixture(context)

    assert {:error, "source commit mismatch"} =
             validate(f, expected_commit: String.duplicate("e", 40))

    assert {:error, "source tree mismatch"} =
             validate(f, expected_tree: String.duplicate("f", 40))
  end

  test "exact destination inventory accepts", context do
    f = fixture(context)
    inventory = write_inventory(context.root, context.migrations)

    assert {:ok, %{mode: "destination-inventory", classification: "clean-source-candidate"}} =
             validate(f, destination_inventory: inventory, artifact_only: false)
  end

  test "validator boundary requires exactly one inventory mode", context do
    f = fixture(context)
    inventory = write_inventory(context.root, context.migrations)

    assert {:error, message} =
             validate(f, artifact_only: false, destination_inventory: nil)

    assert message =~ "destination migration inventory is required"

    assert {:error, "destination inventory and artifact-only are mutually exclusive"} =
             validate(f, artifact_only: true, destination_inventory: inventory)

    assert {:ok, %{mode: "artifact-only"}} =
             validate(f, artifact_only: true, destination_inventory: nil)

    assert {:ok, %{mode: "destination-inventory"}} =
             validate(f, artifact_only: false, destination_inventory: inventory)
  end

  test "destination behind ahead and different reject precisely", context do
    f = fixture(context)
    behind = write_inventory(context.root, Enum.take(context.migrations, 1), "behind.json")
    ahead_migration = %{"path" => "priv/repo/migrations/20260705142136_more.exs", "sha256" => @a}
    ahead = write_inventory(context.root, context.migrations ++ [ahead_migration], "ahead.json")

    different =
      write_inventory(
        context.root,
        [hd(context.migrations), %{List.last(context.migrations) | "sha256" => @a}],
        "different.json"
      )

    assert {:error, "destination migration inventory is behind"} =
             validate(f, destination_inventory: behind, artifact_only: false)

    assert {:error, "destination migration inventory is ahead"} =
             validate(f, destination_inventory: ahead, artifact_only: false)

    assert {:error, "destination migration inventory differs"} =
             validate(f, destination_inventory: different, artifact_only: false)
  end

  test "duplicate unordered malformed and noncanonical destination inventories reject", context do
    f = fixture(context)

    cases = [
      inventory_bytes([hd(context.migrations), hd(context.migrations)]),
      inventory_bytes(Enum.reverse(context.migrations)),
      "{",
      String.trim_trailing(inventory_bytes(context.migrations)),
      ~s({"migrations":"wrong","schema":"spruce-goose-migration-inventory-v1"}\n),
      ~s({"extra":true,"migrations":[],"schema":"spruce-goose-migration-inventory-v1"}\n),
      inventory_bytes([%{"path" => "../bad.exs", "sha256" => @a}]),
      inventory_bytes([%{"path" => hd(context.migrations)["path"], "sha256" => "bad"}])
    ]

    for {bytes, index} <- Enum.with_index(cases) do
      path = Path.join(context.root, "invalid-#{index}.json")
      File.write!(path, bytes)
      assert {:error, _} = validate(f, destination_inventory: path, artifact_only: false)
    end
  end

  test "default inventory refusal, artifact-only acceptance, and destination-looking path remains absent",
       context do
    f = fixture(context)
    destination = Path.join(context.root, "destination-which-must-remain-absent")
    assert {:error, message} = validate(f, artifact_only: false, destination_path: destination)
    assert message =~ "destination migration inventory is required"
    refute File.exists?(destination)

    assert {:ok, %{mode: "artifact-only"}} =
             validate(f, artifact_only: true, destination_path: destination)

    refute File.exists?(destination)
  end

  defp provenance(migrations) do
    %{
      "build" => %{"builder" => "builder", "time_utc" => "2026-08-13T11:18:13Z"},
      "governed" => %{"task" => "tsk-20260813T111813Z-19e119cb", "transaction" => "txn-release"},
      "migration_set_sha256" => ReleaseProvenance.migration_set_digest(migrations),
      "migrations" => migrations,
      "schema" => ReleaseProvenance.provenance_schema(),
      "source" => %{"commit" => @commit, "dirty" => false, "tree" => @tree},
      "toolchain" => %{"elixir" => "1.19.5", "erlang" => "28.3.1", "mix" => "1.19.5"}
    }
  end

  defp fixture(context) do
    bytes = provenance_bytes(context.provenance)
    archive = Path.join(context.root, "release.tar.gz")
    archive_bytes = tar([{~c"releases/0.1.0/governed-provenance.json", bytes}])
    File.write!(archive, archive_bytes)

    receipt_value = %{
      "archive" => %{
        "filename" => Path.basename(archive),
        "sha256" => ReleaseProvenance.sha256(archive_bytes)
      },
      "provenance_sha256" => ReleaseProvenance.sha256(bytes),
      "schema" => ReleaseProvenance.receipt_schema()
    }

    receipt = Path.join(context.root, "receipt.json")
    write_receipt(receipt, receipt_value)
    %{archive: archive, receipt: receipt, receipt_value: receipt_value}
  end

  defp assert_error(f, opts) do
    update = Keyword.fetch!(opts, :receipt_update)
    write_receipt(f.receipt, update.(f.receipt_value))
    assert {:error, Keyword.fetch!(opts, :message)} == validate(f)
  end

  defp validate(f, opts \\ []) do
    defaults = [
      archive: f.archive,
      receipt: f.receipt,
      expected_commit: @commit,
      expected_tree: @tree,
      artifact_only: true
    ]

    ReleaseValidator.validate(Keyword.merge(defaults, opts))
  end

  defp provenance_bytes(p), do: elem(ReleaseProvenance.encode_provenance(p), 1)
  defp write_receipt(path, r), do: File.write!(path, elem(ReleaseProvenance.encode_receipt(r), 1))

  defp write_inventory(root, migrations, name \\ "inventory.json") do
    path = Path.join(root, name)
    File.write!(path, inventory_bytes(migrations))
    path
  end

  defp inventory_bytes(migrations) do
    entries =
      Enum.map_join(migrations, ",", fn m ->
        ~s({"path":"#{m["path"]}","sha256":"#{m["sha256"]}"})
      end)

    ~s({"migrations":[#{entries}],"schema":"spruce-goose-migration-inventory-v1"}\n)
  end

  defp tar(entries) do
    path = Path.join(tmp(), "archive.tar.gz")
    :ok = :erl_tar.create(String.to_charlist(path), entries, [:compressed])
    File.read!(path)
  end

  defp tmp do
    path = Path.join(System.tmp_dir!(), "spruce-provenance-#{System.unique_integer([:positive])}")
    File.rm_rf!(path)
    File.mkdir_p!(path)
    path
  end
end
