defmodule SpruceGoose.Repo.Migrations.LifecycleMembershipAndPermitOutcomeColumns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create constraint(:workflow_tasks, :workflow_tasks_valid_state,
             check: """
               state IN ('inbox','proposed','queued','ready','in_progress','waiting','blocked','completed','failed','cancelled')
             """
           )

    alter table(:knowledge_generations) do
      modify(:state, :text, default: "active")
    end

    alter table(:derivation_permits) do
      remove(:state)
      remove(:executor_id)
      remove(:evidence_digest)
      remove(:artifact_digest)
      remove(:failure_reason)
      remove(:claimed_at)
      remove(:completed_at)
    end
  end

  def down do
    alter table(:derivation_permits) do
      add(:completed_at, :utc_datetime_usec)
      add(:claimed_at, :utc_datetime_usec)
      add(:failure_reason, :text)
      add(:artifact_digest, :text)
      add(:evidence_digest, :text)
      add(:executor_id, :text)
      add(:state, :text, null: false, default: "admitted")
    end

    alter table(:knowledge_generations) do
      modify(:state, :text, default: nil)
    end

    drop_if_exists(constraint(:workflow_tasks, :workflow_tasks_valid_state))
  end
end
