defmodule SpruceGoose.Repo.Migrations.TaskflowShadowSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:taskflow_shadow_snapshots, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:flow_id, :text, null: false)
      add(:revision, :bigint, null: false)
      add(:sync_mode, :text, null: false)
      add(:status, :text, null: false)
      add(:owner_key, :text, null: false)
      add(:current_step, :text)
      add(:state_digest, :text, null: false)
      add(:wait_digest, :text, null: false)
      add(:child_task_count, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :task_id,
        references(:workflow_tasks,
          column: :id,
          name: "taskflow_shadow_snapshots_task_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:taskflow_shadow_snapshots, [:flow_id, :revision],
             name: "taskflow_shadow_snapshots_one_snapshot_per_revision_index"
           )

    execute("""
    CREATE FUNCTION refuse_taskflow_shadow_snapshot_mutation()
    RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION 'TaskFlow shadow snapshots are immutable';
    END;
    $$ LANGUAGE plpgsql;
    """)

    execute("""
    CREATE TRIGGER taskflow_shadow_snapshots_immutable
    BEFORE UPDATE OR DELETE ON taskflow_shadow_snapshots
    FOR EACH ROW EXECUTE FUNCTION refuse_taskflow_shadow_snapshot_mutation();
    """)
  end

  def down do
    execute(
      "DROP TRIGGER IF EXISTS taskflow_shadow_snapshots_immutable ON taskflow_shadow_snapshots"
    )

    execute("DROP FUNCTION IF EXISTS refuse_taskflow_shadow_snapshot_mutation()")

    drop(constraint(:taskflow_shadow_snapshots, "taskflow_shadow_snapshots_task_id_fkey"))

    drop_if_exists(
      unique_index(:taskflow_shadow_snapshots, [:flow_id, :revision],
        name: "taskflow_shadow_snapshots_one_snapshot_per_revision_index"
      )
    )

    drop(table(:taskflow_shadow_snapshots))
  end
end
