defmodule SpruceGoose.Repo.Migrations.AddTaskSopGate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_tasks) do
      add(:sop_gate_required, :boolean, null: false, default: false)
      add(:sop_path, :text)
      add(:sop_digest, :text)
      add(:sop_acknowledged_at, :utc_datetime_usec)
    end

    execute("ALTER TABLE workflow_tasks ALTER COLUMN sop_gate_required SET DEFAULT true")

    create(
      constraint(:workflow_tasks, :workflow_tasks_sop_gate_complete,
        check: """
        NOT sop_gate_required OR (
          sop_path = '/home/admin-papa/.openclaw/vaults/openclaw-system/10-sop/Systemwide SOP.md'
          AND sop_digest ~ '^[0-9a-f]{64}$'
          AND sop_acknowledged_at IS NOT NULL
        )
        """
      )
    )
  end

  def down do
    drop(constraint(:workflow_tasks, :workflow_tasks_sop_gate_complete))

    alter table(:workflow_tasks) do
      remove(:sop_acknowledged_at)
      remove(:sop_digest)
      remove(:sop_path)
      remove(:sop_gate_required)
    end
  end
end
