defmodule SpruceGoose.Repo.Migrations.LegibleBlueprintRevisions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workflow_blueprint_revisions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:revision_id, :text, null: false)
      add(:repository, :text, null: false)
      add(:source_commit, :text, null: false)
      add(:source_tree, :text, null: false)
      add(:source_path, :text, null: false)
      add(:manifest_digest, :text, null: false)
      add(:schema_version, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "workflow_blueprint_revisions_project_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(
             :workflow_blueprint_revisions,
             [:project_id, :repository, :source_commit, :source_path],
             name: "workflow_blueprint_revisions_one_blueprint_per_source_index"
           )

    create unique_index(:workflow_blueprint_revisions, [:revision_id],
             name: "workflow_blueprint_revisions_stable_revision_id_index"
           )
  end

  def down do
    drop(
      constraint(:workflow_blueprint_revisions, "workflow_blueprint_revisions_project_id_fkey")
    )

    drop_if_exists(
      unique_index(:workflow_blueprint_revisions, [:revision_id],
        name: "workflow_blueprint_revisions_stable_revision_id_index"
      )
    )

    drop_if_exists(
      unique_index(
        :workflow_blueprint_revisions,
        [:project_id, :repository, :source_commit, :source_path],
        name: "workflow_blueprint_revisions_one_blueprint_per_source_index"
      )
    )

    drop(table(:workflow_blueprint_revisions))
  end
end
