defmodule SpruceGoose.Repo.Migrations.AddInboxAgentHooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:inbox_triage_results, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:actor_id, :uuid, null: false)
      add(:context_digest, :text, null: false)
      add(:outcome, :text, null: false, default: "proposed")
      add(:proposal, :map)
      add(:proposal_digest, :text)
      add(:reason, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:run_id, :uuid, null: false)
    end

    create unique_index(:inbox_triage_results, [:run_id],
             name: "inbox_triage_results_one_result_per_run_index"
           )

    create table(:agent_hook_runs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:inbox_triage_results) do
      modify(
        :run_id,
        references(:agent_hook_runs,
          column: :id,
          name: "inbox_triage_results_run_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:agent_hook_runs) do
      add(:run_key, :text, null: false)
      add(:event_id, :uuid, null: false)
      add(:event_key, :text, null: false)
      add(:hook_id, :text, null: false)
      add(:hook_version, :bigint, null: false)
      add(:actor_id, :uuid, null: false)
      add(:config_digest, :text, null: false)
      add(:charter_digest, :text, null: false)
      add(:context_digest, :text, null: false)
      add(:context, :map, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :inbox_item_id,
        references(:inbox_items,
          column: :id,
          name: "agent_hook_runs_inbox_item_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:agent_hook_runs, [:run_key],
             name: "agent_hook_runs_stable_run_key_index"
           )
  end

  def down do
    drop(constraint(:agent_hook_runs, "agent_hook_runs_inbox_item_id_fkey"))

    drop_if_exists(
      unique_index(:agent_hook_runs, [:run_key], name: "agent_hook_runs_stable_run_key_index")
    )

    alter table(:agent_hook_runs) do
      remove(:inbox_item_id)
      remove(:inserted_at)
      remove(:context)
      remove(:context_digest)
      remove(:charter_digest)
      remove(:config_digest)
      remove(:actor_id)
      remove(:hook_version)
      remove(:hook_id)
      remove(:event_key)
      remove(:event_id)
      remove(:run_key)
    end

    drop(constraint(:inbox_triage_results, "inbox_triage_results_run_id_fkey"))

    alter table(:inbox_triage_results) do
      modify(:run_id, :uuid)
    end

    drop(table(:agent_hook_runs))

    drop_if_exists(
      unique_index(:inbox_triage_results, [:run_id],
        name: "inbox_triage_results_one_result_per_run_index"
      )
    )

    drop(table(:inbox_triage_results))
  end
end
