defmodule SpruceGoose.Repo.Migrations.BindDerivationPermitRoots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:derivation_permits) do
      # Existing permits predate constitutional roots. Keep them readable and
      # unmodified; the Ash admission action requires roots for every new row.
      add(:roots, :map, null: true)
    end

    execute("""
    CREATE FUNCTION refuse_derivation_permit_mutation() RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION 'derivation permits are immutable';
    END;
    $$ LANGUAGE plpgsql
    """)

    execute("""
    CREATE TRIGGER derivation_permits_immutable
    BEFORE UPDATE OR DELETE ON derivation_permits
    FOR EACH ROW EXECUTE FUNCTION refuse_derivation_permit_mutation()
    """)
  end

  def down do
    execute("DROP TRIGGER IF EXISTS derivation_permits_immutable ON derivation_permits")
    execute("DROP FUNCTION IF EXISTS refuse_derivation_permit_mutation()")

    alter table(:derivation_permits) do
      remove(:roots)
    end
  end
end
