defmodule SpruceGoose.Repo.Migrations.BindTasksToBlueprintDefinitions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_tasks) do
      add(:definition_key, :text)

      add(
        :blueprint_revision_id,
        references(:workflow_blueprint_revisions,
          column: :id,
          name: "workflow_tasks_blueprint_revision_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:workflow_tasks, "workflow_tasks_blueprint_revision_id_fkey"))

    alter table(:workflow_tasks) do
      remove(:blueprint_revision_id)
      remove(:definition_key)
    end
  end
end
