defmodule SpruceGoose.Repo.Migrations.BindDerivationPermitRoots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:derivation_permits) do
      # Existing permits predate constitutional roots. Keep them readable and
      # unmodified; the Ash admission action requires roots for every new row.
      add(:roots, :map, null: true)
    end
  end

  def down do
    alter table(:derivation_permits) do
      remove(:roots)
    end
  end
end
