defmodule SpruceGoose.Repo.Migrations.AddArtifactReceipts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_tasks) do
      add(:artifact_requirements, {:array, :text}, null: false, default: [])
      add(:artifact_receipts, {:array, :map}, null: false, default: [])
    end
  end

  def down do
    alter table(:workflow_tasks) do
      remove(:artifact_receipts)
      remove(:artifact_requirements)
    end
  end
end
