defmodule Orchestrator.Repo.Migrations.HardenAuthorityAndDependencyImport do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:task_dependencies) do
      add(:source, :text, null: false, default: "native")
    end

    execute("""
    UPDATE task_dependencies AS dependency
    SET source = 'tuxedo'
    FROM workflow_tasks AS predecessor, workflow_tasks AS successor
    WHERE predecessor.id = dependency.predecessor_id
      AND successor.id = dependency.successor_id
      AND predecessor.input->>'legacy_source' = 'tuxedo'
      AND successor.input->>'legacy_source' = 'tuxedo'
    """)

    create table(:orchestrator_authority, primary_key: false) do
      add(:id, :boolean, null: false, primary_key: true)
      add(:mode, :text, null: false)
      add(:cutover_at, :utc_datetime_usec)
    end

    create constraint(:orchestrator_authority, :singleton_authority, check: "id = TRUE")

    create constraint(:orchestrator_authority, :valid_authority_mode,
             check: "mode IN ('tuxedo', 'ash')"
           )

    execute("INSERT INTO orchestrator_authority (id, mode) VALUES (TRUE, 'tuxedo')")
  end

  def down do
    drop(table(:orchestrator_authority))

    alter table(:task_dependencies) do
      remove(:source)
    end
  end
end
