defmodule SpruceGoose.Repo.Migrations.AddInboxItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:inbox_items, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:capture_id, :text, null: false)
      add(:body, :text, null: false)
      add(:state, :text, null: false, default: "pending")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:inbox_items, [:capture_id], name: "inbox_items_stable_capture_index")
  end

  def down do
    drop_if_exists(
      unique_index(:inbox_items, [:capture_id], name: "inbox_items_stable_capture_index")
    )

    drop(table(:inbox_items))
  end
end
