defmodule SpruceGoose.Repo.Migrations.BindDerivationReceiptTaskScope do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:derivation_outcome_receipts) do
      add(
        :task_id,
        references(:workflow_tasks,
          column: :id,
          name: "derivation_outcome_receipts_task_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end
  end

  def down do
    drop(constraint(:derivation_outcome_receipts, "derivation_outcome_receipts_task_id_fkey"))

    alter table(:derivation_outcome_receipts) do
      remove(:task_id)
    end
  end
end
