defmodule SpruceGoose.Repo.Migrations.AddDerivationOutcomeReceipts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:derivation_outcome_receipts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:receipt_id, :text, null: false)
      add(:permit_id, :text, null: false)
      add(:executor_id, :text, null: false)
      add(:outcome, :text, null: false)
      add(:evidence_digest, :text)
      add(:artifact_digest, :text)
      add(:failure_reason, :text)
      add(:roots, :map, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:derivation_outcome_receipts, [:permit_id],
             name: "derivation_receipts_one_permit_idx"
           )

    create unique_index(:derivation_outcome_receipts, [:receipt_id],
             name: "derivation_outcome_receipts_stable_receipt_id_index"
           )

    execute("""
    ALTER TABLE derivation_outcome_receipts
      ADD CONSTRAINT derivation_receipt_outcome_shape CHECK (
        (outcome = 'succeeded' AND evidence_digest ~ '^[0-9a-f]{64}$' AND failure_reason IS NULL) OR
        (outcome = 'failed' AND failure_reason IS NOT NULL AND evidence_digest IS NULL AND artifact_digest IS NULL)
      ),
      ADD CONSTRAINT derivation_receipt_artifact_digest CHECK (
        artifact_digest IS NULL OR artifact_digest ~ '^[0-9a-f]{64}$'
      ),
      ADD CONSTRAINT derivation_receipt_permit_fk FOREIGN KEY (permit_id)
        REFERENCES derivation_permits(permit_id)
    """)

    execute("""
    CREATE FUNCTION refuse_derivation_receipt_mutation() RETURNS trigger AS $$
    BEGIN
      RAISE EXCEPTION 'derivation outcome receipts are immutable';
    END;
    $$ LANGUAGE plpgsql
    """)

    execute("""
    CREATE TRIGGER derivation_outcome_receipts_immutable
    BEFORE UPDATE OR DELETE ON derivation_outcome_receipts
    FOR EACH ROW EXECUTE FUNCTION refuse_derivation_receipt_mutation()
    """)
  end

  def down do
    execute(
      "DROP TRIGGER IF EXISTS derivation_outcome_receipts_immutable ON derivation_outcome_receipts"
    )

    execute("DROP FUNCTION IF EXISTS refuse_derivation_receipt_mutation()")

    drop_if_exists(
      unique_index(:derivation_outcome_receipts, [:receipt_id],
        name: "derivation_outcome_receipts_stable_receipt_id_index"
      )
    )

    drop_if_exists(
      unique_index(:derivation_outcome_receipts, [:permit_id],
        name: "derivation_receipts_one_permit_idx"
      )
    )

    drop(table(:derivation_outcome_receipts))
  end
end
