defmodule SpruceGoose.Repo.Migrations.AddInboxTriage do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inbox_items) do
      add(:resolution_reason, :text)
      add(:promoted_task_id, :text)
      add(:resolved_at, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:inbox_items) do
      remove(:resolved_at)
      remove(:promoted_task_id)
      remove(:resolution_reason)
    end
  end
end
