defmodule SpruceGoose.Repo.Migrations.AddActorRegistry do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:revisions) do
      add(:project_key, :text)
      add(:self_approved, :boolean, null: false, default: false)
    end

    create table(:actors, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:kind, :text, null: false)
      add(:description, :text)
      add(:disabled_at, :utc_datetime_usec)
      add(:disabled_reason, :text)
      add(:created_by, :text, null: false)
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:actors, [:name], name: "actors_unique_actor_name_index")

    create table(:actor_grants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:role, :text, null: false)
      add(:scope, :text, null: false)
      add(:granted_by, :text, null: false)
      add(:granted_at, :utc_datetime_usec, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :actor_id,
        references(:actors,
          column: :id,
          name: "actor_grants_actor_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:actor_grants, [:actor_id, :role, :scope],
             name: "actor_grants_unique_grant_index"
           )
  end

  def down do
    drop(constraint(:actor_grants, "actor_grants_actor_id_fkey"))

    drop_if_exists(
      unique_index(:actor_grants, [:actor_id, :role, :scope],
        name: "actor_grants_unique_grant_index"
      )
    )

    drop(table(:actor_grants))

    drop_if_exists(unique_index(:actors, [:name], name: "actors_unique_actor_name_index"))

    drop(table(:actors))

    alter table(:revisions) do
      remove(:self_approved)
      remove(:project_key)
    end
  end
end
