defmodule SpruceGoose.Repo.Migrations.AddOrchestrationHierarchy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:projects, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:key, :text, null: false)
      add(:name, :text, null: false)

      timestamps(type: :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')"))
    end

    create(unique_index(:projects, [:key], name: "projects_unique_project_key_index"))

    create table(:roadmaps, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:key, :text, null: false)
      add(:name, :text, null: false)

      timestamps(type: :utc_datetime_usec, default: fragment("(now() AT TIME ZONE 'utc')"))

      add(
        :project_id,
        references(:projects,
          column: :id,
          name: "roadmaps_project_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      unique_index(:roadmaps, [:project_id, :key],
        name: "roadmaps_unique_roadmap_key_per_project_index"
      )
    )

    execute("""
    INSERT INTO projects (key, name)
    VALUES ('legacy-import', 'Legacy import')
    ON CONFLICT (key) DO NOTHING
    """)

    execute("""
    INSERT INTO roadmaps (project_id, key, name)
    SELECT id, 'legacy-import', 'Legacy import'
    FROM projects
    WHERE key = 'legacy-import'
    ON CONFLICT (project_id, key) DO NOTHING
    """)

    alter table(:workflows) do
      add(:name, :text)
      add(:roadmap_id, :uuid)
    end

    execute("""
    UPDATE workflows
    SET name = workflow_id,
        roadmap_id = (
          SELECT roadmaps.id
          FROM roadmaps
          JOIN projects ON projects.id = roadmaps.project_id
          WHERE projects.key = 'legacy-import'
            AND roadmaps.key = 'legacy-import'
        )
    WHERE name IS NULL OR roadmap_id IS NULL
    """)

    alter table(:workflows) do
      modify(:name, :text, null: false)

      modify(
        :roadmap_id,
        references(:roadmaps,
          column: :id,
          name: "workflows_roadmap_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    drop_if_exists(
      unique_index(:workflows, [:workflow_id], name: "workflows_unique_workflow_id_index")
    )

    create(
      unique_index(:workflows, [:roadmap_id, :workflow_id],
        name: "workflows_unique_workflow_id_per_roadmap_index"
      )
    )

    create table(:workflow_tasks, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:task_id, :text, null: false)
      add(:title, :text, null: false)
      add(:definition_of_done, :text, null: false)
      add(:state, :text, null: false, default: "inbox")
      add(:runner, :text, null: false)
      add(:input, :map, null: false, default: %{})
      add(:origin_event_id, :text)
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :workflow_id,
        references(:workflows,
          column: :id,
          name: "workflow_tasks_workflow_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      unique_index(:workflow_tasks, [:origin_event_id],
        name: "workflow_tasks_idempotent_origin_event_index"
      )
    )

    create(unique_index(:workflow_tasks, [:task_id], name: "workflow_tasks_stable_task_id_index"))

    create table(:task_todos, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:todo_id, :text, null: false)
      add(:body, :text, null: false)
      add(:position, :bigint, null: false)
      add(:completed, :boolean, null: false, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :task_id,
        references(:workflow_tasks,
          column: :id,
          name: "task_todos_task_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      unique_index(:task_todos, [:task_id, :position],
        name: "task_todos_stable_position_per_task_index"
      )
    )

    create(
      unique_index(:task_todos, [:task_id, :todo_id],
        name: "task_todos_stable_todo_per_task_index"
      )
    )

    create table(:task_dependencies, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :predecessor_id,
        references(:workflow_tasks,
          column: :id,
          name: "task_dependencies_predecessor_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :successor_id,
        references(:workflow_tasks,
          column: :id,
          name: "task_dependencies_successor_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create(
      unique_index(:task_dependencies, [:predecessor_id, :successor_id],
        name: "task_dependencies_unique_dependency_index"
      )
    )

    create(
      constraint(:task_dependencies, :not_self_dependency,
        check: """
          predecessor_id <> successor_id
        """
      )
    )
  end

  def down do
    drop_if_exists(constraint(:task_dependencies, :not_self_dependency))

    drop_if_exists(unique_index(:projects, [:key], name: "projects_unique_project_key_index"))

    alter table(:projects) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:name)
      remove(:key)
    end

    drop(constraint(:roadmaps, "roadmaps_project_id_fkey"))

    alter table(:roadmaps) do
      modify(:project_id, :uuid)
    end

    drop(table(:projects))

    drop_if_exists(
      unique_index(:roadmaps, [:project_id, :key],
        name: "roadmaps_unique_roadmap_key_per_project_index"
      )
    )

    alter table(:roadmaps) do
      remove(:project_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:name)
      remove(:key)
    end

    drop(constraint(:workflows, "workflows_roadmap_id_fkey"))

    alter table(:workflows) do
      modify(:roadmap_id, :uuid)
    end

    drop(table(:roadmaps))

    drop(constraint(:task_dependencies, "task_dependencies_predecessor_id_fkey"))

    drop(constraint(:task_dependencies, "task_dependencies_successor_id_fkey"))

    drop_if_exists(
      unique_index(:task_dependencies, [:predecessor_id, :successor_id],
        name: "task_dependencies_unique_dependency_index"
      )
    )

    drop(table(:task_dependencies))

    drop(constraint(:task_todos, "task_todos_task_id_fkey"))

    drop_if_exists(
      unique_index(:task_todos, [:task_id, :todo_id],
        name: "task_todos_stable_todo_per_task_index"
      )
    )

    drop_if_exists(
      unique_index(:task_todos, [:task_id, :position],
        name: "task_todos_stable_position_per_task_index"
      )
    )

    drop(table(:task_todos))

    drop(constraint(:workflow_tasks, "workflow_tasks_workflow_id_fkey"))

    drop_if_exists(
      unique_index(:workflow_tasks, [:task_id], name: "workflow_tasks_stable_task_id_index")
    )

    drop_if_exists(
      unique_index(:workflow_tasks, [:origin_event_id],
        name: "workflow_tasks_idempotent_origin_event_index"
      )
    )

    drop(table(:workflow_tasks))

    drop_if_exists(
      unique_index(:workflows, [:roadmap_id, :workflow_id],
        name: "workflows_unique_workflow_id_per_roadmap_index"
      )
    )

    create(unique_index(:workflows, [:workflow_id], name: "workflows_unique_workflow_id_index"))

    alter table(:workflows) do
      remove(:roadmap_id)
      remove(:name)
    end
  end
end
