defmodule SpruceGoose.Repo.Migrations.AddTypedDerivationArtifactInput do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:derivation_permits) do
      add(:input_artifact_digest, :text)
    end

    execute("""
    DO $$
    BEGIN
      IF EXISTS (
        SELECT 1
        FROM derivation_permits
        WHERE action = 'verify_artifact'
      ) THEN
        RAISE EXCEPTION
          'existing verify_artifact permits have no provable input content ID';
      END IF;
    END
    $$
    """)

    create constraint(:derivation_permits, :typed_derivation_input,
             check: """
               (action = 'verify_artifact' AND input_artifact_digest ~ '^[0-9a-f]{64}$') OR (action <> 'verify_artifact' AND input_artifact_digest IS NULL)
             """
           )
  end

  def down do
    drop_if_exists(constraint(:derivation_permits, :typed_derivation_input))

    alter table(:derivation_permits) do
      remove(:input_artifact_digest)
    end
  end
end
