defmodule SpruceGoose.Repo.Migrations.RemediateSopGate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_tasks) do
      add(:sop_id, :text)
    end

    execute("""
    UPDATE workflow_tasks
    SET sop_id = 'systemwide-sop'
    WHERE sop_gate_required
    """)

    drop(constraint(:workflow_tasks, :workflow_tasks_sop_gate_complete))

    create(
      constraint(:workflow_tasks, :workflow_tasks_sop_gate_complete,
        check: """
        NOT sop_gate_required OR (
          sop_id = 'systemwide-sop'
          AND length(btrim(sop_path)) > 0
          AND sop_digest ~ '^[0-9a-f]{64}$'
          AND sop_acknowledged_at IS NOT NULL
        )
        """
      )
    )
  end

  def down do
    drop(constraint(:workflow_tasks, :workflow_tasks_sop_gate_complete))

    create(
      constraint(:workflow_tasks, :workflow_tasks_sop_gate_complete,
        check: """
        NOT sop_gate_required OR (
          sop_path = '/home/admin-papa/.openclaw/vaults/openclaw-system/10-sop/Systemwide SOP.md'
          AND sop_digest ~ '^[0-9a-f]{64}$'
          AND sop_acknowledged_at IS NOT NULL
        )
        """
      )
    )

    alter table(:workflow_tasks) do
      remove(:sop_id)
    end
  end
end
