defmodule SpruceGoose.Repo.Migrations.IntakeFrontDoor do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:inbox_items) do
      add(:request_type, :text)
      add(:priority, :bigint)
      add(:title, :text)
      add(:definition_of_done, :text)
      add(:proposed_project, :text)
      add(:proposed_roadmap, :text)
      add(:proposed_workflow, :text)
      add(:classified_at, :utc_datetime_usec)
    end
  end

  def down do
    alter table(:inbox_items) do
      remove(:classified_at)
      remove(:proposed_workflow)
      remove(:proposed_roadmap)
      remove(:proposed_project)
      remove(:definition_of_done)
      remove(:title)
      remove(:priority)
      remove(:request_type)
    end
  end
end
