defmodule SpruceGoose.Repo.Migrations.HardenPostCutoverInvariants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:board_columns, [:board_id, :task_state],
             name: "board_columns_unique_column_state_per_board_index"
           )

    create(
      constraint(:workflow_tasks, :workflow_tasks_priority_range,
        check: "priority IS NULL OR priority BETWEEN 0 AND 5"
      )
    )

    create(
      constraint(:workflow_tasks, :workflow_tasks_rank_shape,
        check: "rank IS NULL OR (octet_length(btrim(rank)) BETWEEN 1 AND 128)"
      )
    )

    create(
      constraint(:workflow_tasks, :workflow_tasks_metadata_collection_limits,
        check: "cardinality(assignees) <= 50 AND cardinality(labels) <= 50"
      )
    )

    create(
      constraint(:board_columns, :board_columns_valid_task_state,
        check:
          "task_state IN ('inbox','proposed','queued','ready','in_progress','waiting','blocked','completed','failed','cancelled')"
      )
    )

    execute("""
    CREATE FUNCTION enforce_irreversible_authority()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF OLD.mode = 'tuxedo'
         AND OLD.cutover_at IS NULL
         AND NEW.mode = 'ash'
         AND NEW.cutover_at IS NOT NULL THEN
        RETURN NEW;
      END IF;

      RAISE EXCEPTION 'orchestrator authority cutover is irreversible'
        USING ERRCODE = '23514';
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER orchestrator_authority_irreversible
    BEFORE UPDATE ON orchestrator_authority
    FOR EACH ROW
    EXECUTE FUNCTION enforce_irreversible_authority();
    """)

    execute("""
    CREATE FUNCTION enforce_todo_task_state()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    DECLARE
      owner_state text;
    BEGIN
      SELECT state INTO owner_state
      FROM workflow_tasks
      WHERE id = NEW.task_id
      FOR UPDATE;

      IF owner_state IN ('completed', 'cancelled') THEN
        RAISE EXCEPTION 'cannot add TODO to terminal task'
          USING ERRCODE = '23514';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER task_todos_terminal_guard
    BEFORE INSERT ON task_todos
    FOR EACH ROW
    EXECUTE FUNCTION enforce_todo_task_state();
    """)

    execute("""
    CREATE FUNCTION enforce_task_completion_todos()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF NEW.state = 'completed'
         AND OLD.state IS DISTINCT FROM NEW.state
         AND EXISTS (
           SELECT 1 FROM task_todos
           WHERE task_id = NEW.id AND completed = FALSE
         ) THEN
        RAISE EXCEPTION 'cannot complete task with incomplete TODOs'
          USING ERRCODE = '23514';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER workflow_tasks_completion_todo_guard
    BEFORE UPDATE OF state ON workflow_tasks
    FOR EACH ROW
    EXECUTE FUNCTION enforce_task_completion_todos();
    """)

    execute("""
    CREATE OR REPLACE FUNCTION enforce_task_board_membership()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF NEW.column_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM board_columns AS bc
        JOIN boards AS board ON board.id = bc.board_id
        WHERE bc.id = NEW.column_id
          AND board.id = NEW.board_id
          AND board.workflow_id = NEW.workflow_id
          AND bc.task_state = NEW.state
      ) THEN
        RAISE EXCEPTION 'task board, column, workflow, and state must agree'
          USING ERRCODE = '23514';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("DROP TRIGGER workflow_tasks_board_membership ON workflow_tasks")

    execute("""
    CREATE TRIGGER workflow_tasks_board_membership
    BEFORE INSERT OR UPDATE OF board_id, column_id, workflow_id, state
    ON workflow_tasks
    FOR EACH ROW
    EXECUTE FUNCTION enforce_task_board_membership();
    """)
  end

  def down do
    execute("DROP TRIGGER workflow_tasks_board_membership ON workflow_tasks")

    execute("""
    CREATE OR REPLACE FUNCTION enforce_task_board_membership()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF NEW.column_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM board_columns
        WHERE id = NEW.column_id AND board_id = NEW.board_id
      ) THEN
        RAISE EXCEPTION 'task board and column must belong to the same board'
          USING ERRCODE = '23514';
      END IF;
      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER workflow_tasks_board_membership
    BEFORE INSERT OR UPDATE OF board_id, column_id
    ON workflow_tasks
    FOR EACH ROW
    EXECUTE FUNCTION enforce_task_board_membership();
    """)

    execute("DROP TRIGGER IF EXISTS workflow_tasks_completion_todo_guard ON workflow_tasks")
    execute("DROP FUNCTION IF EXISTS enforce_task_completion_todos()")
    execute("DROP TRIGGER IF EXISTS task_todos_terminal_guard ON task_todos")
    execute("DROP FUNCTION IF EXISTS enforce_todo_task_state()")

    execute(
      "DROP TRIGGER IF EXISTS orchestrator_authority_irreversible ON orchestrator_authority"
    )

    execute("DROP FUNCTION IF EXISTS enforce_irreversible_authority()")
    drop(constraint(:board_columns, :board_columns_valid_task_state))
    drop(constraint(:workflow_tasks, :workflow_tasks_metadata_collection_limits))
    drop(constraint(:workflow_tasks, :workflow_tasks_rank_shape))
    drop(constraint(:workflow_tasks, :workflow_tasks_priority_range))

    drop_if_exists(
      unique_index(:board_columns, [:board_id, :task_state],
        name: "board_columns_unique_column_state_per_board_index"
      )
    )
  end
end
