defmodule SpruceGoose.Repo.Migrations.AddKanbanBoardMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_tasks) do
      add(:description, :text)
      add(:rank, :text)
      add(:priority, :bigint)
      add(:due_at, :utc_datetime_usec)
      add(:assignees, {:array, :text}, null: false, default: [])
      add(:labels, {:array, :text}, null: false, default: [])
      add(:custom_fields, :map, null: false, default: %{})
      add(:board_revision, :bigint, null: false, default: 1)
      add(:board_id, :uuid)
      add(:column_id, :uuid)
    end

    create table(:saved_filters, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:criteria, :map, null: false, default: %{})

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:board_id, :uuid, null: false)
    end

    create unique_index(:saved_filters, [:board_id, :name],
             name: "saved_filters_unique_filter_name_per_board_index"
           )

    create table(:boards, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:workflow_tasks) do
      modify(
        :board_id,
        references(:boards,
          column: :id,
          name: "workflow_tasks_board_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:saved_filters) do
      modify(
        :board_id,
        references(:boards,
          column: :id,
          name: "saved_filters_board_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:boards) do
      add(:key, :text, null: false)
      add(:name, :text, null: false)
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :workflow_id,
        references(:workflows,
          column: :id,
          name: "boards_workflow_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:boards, [:workflow_id, :key],
             name: "boards_unique_board_key_per_workflow_index"
           )

    create table(:board_columns, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:workflow_tasks) do
      modify(
        :column_id,
        references(:board_columns,
          column: :id,
          name: "workflow_tasks_column_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:board_columns) do
      add(:key, :text, null: false)
      add(:name, :text, null: false)
      add(:position, :bigint, null: false)
      add(:task_state, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :board_id,
        references(:boards,
          column: :id,
          name: "board_columns_board_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:board_columns, [:board_id, :key],
             name: "board_columns_unique_column_key_per_board_index"
           )

    create unique_index(:board_columns, [:board_id, :position],
             name: "board_columns_unique_column_position_per_board_index"
           )

    create(
      constraint(:workflow_tasks, :workflow_tasks_board_column_pair,
        check: "(board_id IS NULL) = (column_id IS NULL)"
      )
    )

    execute("""
    CREATE FUNCTION enforce_task_board_membership()
    RETURNS trigger
    LANGUAGE plpgsql
    AS $$
    BEGIN
      IF NEW.column_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM board_columns
        WHERE id = NEW.column_id
          AND board_id = NEW.board_id
      ) THEN
        RAISE EXCEPTION 'task board and column must belong to the same board'
          USING ERRCODE = '23514';
      END IF;

      RETURN NEW;
    END;
    $$;
    """)

    execute("""
    CREATE TRIGGER workflow_tasks_board_membership
    BEFORE INSERT OR UPDATE OF board_id, column_id
    ON workflow_tasks
    FOR EACH ROW
    EXECUTE FUNCTION enforce_task_board_membership();
    """)
  end

  def down do
    execute("DROP TRIGGER IF EXISTS workflow_tasks_board_membership ON workflow_tasks")
    execute("DROP FUNCTION IF EXISTS enforce_task_board_membership()")
    drop(constraint(:workflow_tasks, :workflow_tasks_board_column_pair))

    drop(constraint(:board_columns, "board_columns_board_id_fkey"))

    drop_if_exists(
      unique_index(:board_columns, [:board_id, :position],
        name: "board_columns_unique_column_position_per_board_index"
      )
    )

    drop_if_exists(
      unique_index(:board_columns, [:board_id, :key],
        name: "board_columns_unique_column_key_per_board_index"
      )
    )

    alter table(:board_columns) do
      remove(:board_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:task_state)
      remove(:position)
      remove(:name)
      remove(:key)
    end

    drop(constraint(:workflow_tasks, "workflow_tasks_column_id_fkey"))

    alter table(:workflow_tasks) do
      modify(:column_id, :uuid)
    end

    drop(table(:board_columns))

    drop(constraint(:boards, "boards_workflow_id_fkey"))

    drop_if_exists(
      unique_index(:boards, [:workflow_id, :key],
        name: "boards_unique_board_key_per_workflow_index"
      )
    )

    alter table(:boards) do
      remove(:workflow_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:lock_version)
      remove(:name)
      remove(:key)
    end

    drop(constraint(:saved_filters, "saved_filters_board_id_fkey"))

    alter table(:saved_filters) do
      modify(:board_id, :uuid)
    end

    drop(constraint(:workflow_tasks, "workflow_tasks_board_id_fkey"))

    alter table(:workflow_tasks) do
      modify(:board_id, :uuid)
    end

    drop(table(:boards))

    drop_if_exists(
      unique_index(:saved_filters, [:board_id, :name],
        name: "saved_filters_unique_filter_name_per_board_index"
      )
    )

    drop(table(:saved_filters))

    alter table(:workflow_tasks) do
      remove(:column_id)
      remove(:board_id)
      remove(:board_revision)
      remove(:custom_fields)
      remove(:labels)
      remove(:assignees)
      remove(:due_at)
      remove(:priority)
      remove(:rank)
      remove(:description)
    end
  end
end
