defmodule Orchestrator.Repo.Migrations.AddWorkflowDefinitions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workflows, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:workflow_id, :text, null: false)
      add(:definition, :map, null: false)
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:workflows, [:workflow_id], name: "workflows_unique_workflow_id_index"))
  end

  def down do
    drop_if_exists(
      unique_index(:workflows, [:workflow_id], name: "workflows_unique_workflow_id_index")
    )

    drop(table(:workflows))
  end
end
