defmodule SpruceGoose.Repo.Migrations.AddSopVersion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:workflow_tasks) do
      add(:sop_version, :text)
    end
  end

  def down do
    alter table(:workflow_tasks) do
      remove(:sop_version)
    end
  end
end
