defmodule SpruceGoose.Repo.Migrations.AddTodoDependencies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:task_todo_dependencies, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:task_id, :uuid, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :predecessor_id,
        references(:task_todos,
          column: :id,
          name: "task_todo_dependencies_predecessor_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :successor_id,
        references(:task_todos,
          column: :id,
          name: "task_todo_dependencies_successor_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:task_todo_dependencies, [:predecessor_id, :successor_id],
             name: "task_todo_dependencies_unique_todo_dependency_index"
           )

    create constraint(:task_todo_dependencies, :todo_not_self_dependency,
             check: """
               predecessor_id <> successor_id
             """
           )
  end

  def down do
    drop_if_exists(constraint(:task_todo_dependencies, :todo_not_self_dependency))

    drop(constraint(:task_todo_dependencies, "task_todo_dependencies_predecessor_id_fkey"))

    drop(constraint(:task_todo_dependencies, "task_todo_dependencies_successor_id_fkey"))

    drop_if_exists(
      unique_index(:task_todo_dependencies, [:predecessor_id, :successor_id],
        name: "task_todo_dependencies_unique_todo_dependency_index"
      )
    )

    drop(table(:task_todo_dependencies))
  end
end
