defmodule SpruceGoose.Repo.Migrations.TypedDerivationPermits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:derivation_permits, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:permit_id, :text, null: false)
      add(:source_event_id, :text, null: false)
      add(:forge_instance, :text, null: false)
      add(:repository, :text, null: false)
      add(:commit_sha, :text, null: false)
      add(:tree_sha, :text, null: false)
      add(:ref, :text, null: false)
      add(:pipeline_digest, :text, null: false)
      add(:action, :text, null: false)
      add(:state, :text, null: false, default: "admitted")
      add(:executor_id, :text)
      add(:evidence_digest, :text)
      add(:artifact_digest, :text)
      add(:failure_reason, :text)
      add(:claimed_at, :utc_datetime_usec)
      add(:completed_at, :utc_datetime_usec)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :task_id,
        references(:workflow_tasks,
          column: :id,
          name: "derivation_permits_task_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    create unique_index(:derivation_permits, [:source_event_id],
             name: "derivation_permits_one_per_source_event_index"
           )

    create unique_index(:derivation_permits, [:permit_id],
             name: "derivation_permits_stable_permit_id_index"
           )
  end

  def down do
    drop(constraint(:derivation_permits, "derivation_permits_task_id_fkey"))

    drop_if_exists(
      unique_index(:derivation_permits, [:permit_id],
        name: "derivation_permits_stable_permit_id_index"
      )
    )

    drop_if_exists(
      unique_index(:derivation_permits, [:source_event_id],
        name: "derivation_permits_one_per_source_event_index"
      )
    )

    drop(table(:derivation_permits))
  end
end
