defmodule SpruceGoose.Repo.Migrations.AddRevisionsAndLockVersions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:saved_filters) do
      add(:lock_version, :bigint, null: false, default: 1)
    end

    alter table(:roadmaps) do
      add(:lock_version, :bigint, null: false, default: 1)
    end

    create table(:revisions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:revision_id, :text, null: false)
      add(:target_kind, :text, null: false)
      add(:target_id, :uuid, null: false)
      add(:target_ref, :text, null: false)
      add(:expect_lock_version, :bigint, null: false)
      add(:change, :map, null: false, default: %{})
      add(:reason, :text, null: false)
      add(:source_path, :text, null: false)
      add(:source_body, :text, null: false)
      add(:source_digest, :text, null: false)
      add(:state, :text, null: false, default: "pending")
      add(:proposed_by, :text, null: false)
      add(:proposed_at, :utc_datetime_usec, null: false)
      add(:approved_by, :text)
      add(:approved_at, :utc_datetime_usec)
      add(:authorizing_task_id, :text)
      add(:applied_lock_version, :bigint)
      add(:withdrawn_reason, :text)
      add(:lock_version, :bigint, null: false, default: 1)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:revisions, [:revision_id], name: "revisions_stable_revision_id_index")

    alter table(:board_columns) do
      add(:lock_version, :bigint, null: false, default: 1)
    end
  end

  def down do
    alter table(:board_columns) do
      remove(:lock_version)
    end

    drop_if_exists(
      unique_index(:revisions, [:revision_id], name: "revisions_stable_revision_id_index")
    )

    drop(table(:revisions))

    alter table(:roadmaps) do
      remove(:lock_version)
    end

    alter table(:saved_filters) do
      remove(:lock_version)
    end
  end
end
