defmodule SpruceGoose.Repo.Migrations.AddKnowledgeProjection do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:knowledge_relations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:generation_id, :uuid, null: false)
      add(:source, :text, null: false)
      add(:target, :text, null: false)
      add(:relation, :text, null: false)
      add(:confidence, :text, null: false)
      add(:source_file, :text, null: false)
      add(:source_location, :text, null: false)
      add(:origin, :text, null: false)
      add(:position, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:knowledge_relations, [:generation_id, :position],
             name: "knowledge_relations_unique_relation_position_index"
           )

    create table(:knowledge_nodes, primary_key: false) do
      add(:row_id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:generation_id, :uuid, null: false)
      add(:id, :text, null: false)
      add(:label, :text, null: false)
      add(:source_file, :text, null: false)
      add(:source_location, :text, null: false)
      add(:origin, :text, null: false)
      add(:position, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:knowledge_nodes, [:generation_id, :id],
             name: "knowledge_nodes_unique_node_per_generation_index"
           )

    create unique_index(:knowledge_nodes, [:generation_id, :position],
             name: "knowledge_nodes_unique_node_position_index"
           )

    create table(:knowledge_generations, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:knowledge_relations) do
      modify(
        :generation_id,
        references(:knowledge_generations,
          column: :id,
          name: "knowledge_relations_generation_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:knowledge_nodes) do
      modify(
        :generation_id,
        references(:knowledge_generations,
          column: :id,
          name: "knowledge_nodes_generation_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:knowledge_generations) do
      add(:source, :text, null: false)
      add(:source_revision, :text, null: false)
      add(:source_digest, :text, null: false)
      add(:state, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:knowledge_generations, [:source_digest],
             name: "knowledge_generations_unique_source_digest_index"
           )
  end

  def down do
    drop_if_exists(
      unique_index(:knowledge_generations, [:source_digest],
        name: "knowledge_generations_unique_source_digest_index"
      )
    )

    alter table(:knowledge_generations) do
      remove(:updated_at)
      remove(:inserted_at)
      remove(:state)
      remove(:source_digest)
      remove(:source_revision)
      remove(:source)
    end

    drop(constraint(:knowledge_nodes, "knowledge_nodes_generation_id_fkey"))

    alter table(:knowledge_nodes) do
      modify(:generation_id, :uuid)
    end

    drop(constraint(:knowledge_relations, "knowledge_relations_generation_id_fkey"))

    alter table(:knowledge_relations) do
      modify(:generation_id, :uuid)
    end

    drop(table(:knowledge_generations))

    drop_if_exists(
      unique_index(:knowledge_nodes, [:generation_id, :position],
        name: "knowledge_nodes_unique_node_position_index"
      )
    )

    drop_if_exists(
      unique_index(:knowledge_nodes, [:generation_id, :id],
        name: "knowledge_nodes_unique_node_per_generation_index"
      )
    )

    drop(table(:knowledge_nodes))

    drop_if_exists(
      unique_index(:knowledge_relations, [:generation_id, :position],
        name: "knowledge_relations_unique_relation_position_index"
      )
    )

    drop(table(:knowledge_relations))
  end
end
